version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1026:1026
      - 8026:8026

